# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'perf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nperf.proto\x12\x04perf\"\x1e\n\x0b\x44\x61taRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x1f\n\x0c\x44\x61taResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\x46\n\x0bPerfService\x12\x37\n\x0c\x45xchangeData\x12\x11.perf.DataRequest\x1a\x12.perf.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=20
  _globals['_DATAREQUEST']._serialized_end=50
  _globals['_DATARESPONSE']._serialized_start=52
  _globals['_DATARESPONSE']._serialized_end=83
  _globals['_PERFSERVICE']._serialized_start=85
  _globals['_PERFSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
